//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EComerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TReseniaProducto
    {
        public int RPId { get; set; }
        public int REstrellas { get; set; }
        public string RComentarios { get; set; }
        public int PId { get; set; }
        public int UId { get; set; }
        public System.DateTime RPFCreacion { get; set; }
    
        public virtual TProducto TProducto { get; set; }
        public virtual TUsuario TUsuario { get; set; }
    }
}
