//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EComerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUsuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUsuario()
        {
            this.TCarrito = new HashSet<TCarrito>();
            this.TListaDeseos = new HashSet<TListaDeseos>();
            this.TPedido = new HashSet<TPedido>();
            this.TReseniaProducto = new HashSet<TReseniaProducto>();
        }
    
        public int UId { get; set; }
        public string Nombre { get; set; }
        public string UNombre { get; set; }
        public string UCelular { get; set; }
        public string UEmail { get; set; }
        public string UDireccion { get; set; }
        public string UContrasenia { get; set; }
        public string UImagenUrl { get; set; }
        public int RId { get; set; }
        public System.DateTime UFCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCarrito> TCarrito { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TListaDeseos> TListaDeseos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPedido> TPedido { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TReseniaProducto> TReseniaProducto { get; set; }
        public virtual TRoles TRoles { get; set; }
    }
}
