//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EComerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TContacto
    {
        public int CtId { get; set; }
        public string CtNombre { get; set; }
        public string CtEmail { get; set; }
        public string CtAsunto { get; set; }
        public string CtMensaje { get; set; }
        public System.DateTime CtFCreacion { get; set; }
    }
}
