//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EComerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TImagenProducto
    {
        public int IPId { get; set; }
        public string IPUrl { get; set; }
        public int PId { get; set; }
        public Nullable<bool> IPPredeterminado { get; set; }
    
        public virtual TProducto TProducto { get; set; }
    }
}
