//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EComerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPago
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPago()
        {
            this.TPedido = new HashSet<TPedido>();
        }
    
        public int PagId { get; set; }
        public string PagNombre { get; set; }
        public string PagNoTarjeta { get; set; }
        public string PagFvencimiento { get; set; }
        public string PagCvvNo { get; set; }
        public string PagEmail { get; set; }
        public string PagTipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPedido> TPedido { get; set; }
    }
}
