//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EComerce
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TProducto()
        {
            this.TCarrito = new HashSet<TCarrito>();
            this.TImagenProducto = new HashSet<TImagenProducto>();
            this.TListaDeseos = new HashSet<TListaDeseos>();
            this.TPedido = new HashSet<TPedido>();
            this.TReseniaProducto = new HashSet<TReseniaProducto>();
        }
    
        public int PId { get; set; }
        public string PNombre { get; set; }
        public string PDesctipcionCorta { get; set; }
        public string PDesctipcionLarga { get; set; }
        public string PDescripcionAdicional { get; set; }
        public decimal PPprecio { get; set; }
        public int PCantidad { get; set; }
        public string PTamanio { get; set; }
        public string PColor { get; set; }
        public string PCompaniaNombre { get; set; }
        public int CId { get; set; }
        public int SCId { get; set; }
        public Nullable<int> PVendido { get; set; }
        public bool PPersonalizado { get; set; }
        public bool PActivo { get; set; }
        public System.DateTime PFCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TCarrito> TCarrito { get; set; }
        public virtual TCategoria TCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TImagenProducto> TImagenProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TListaDeseos> TListaDeseos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPedido> TPedido { get; set; }
        public virtual TSubCategoria TSubCategoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TReseniaProducto> TReseniaProducto { get; set; }
    }
}
